version: "3.7"
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "6603:3306"
    environment:
      MYSQL_DATABASE: clean
      MYSQL_USER: ijulll
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "8080:80"
    networks:
      - app-network

  nginx:
    image: ijull/nginx-proxy:latest
    restart: always
    volumes:
      - "./:/usr/share/nginx/html"
    environment:
      # NGINX-PROXY ENVIRONMENT VARIABLES: UPDATE ME
      - VIRTUAL_HOST=movie.phantasma.my.id
      - VIRTUAL_PORT=9090
      - LETSENCRYPT_HOST=movie.phantasma.my.id
      - LETSENCRYPT_EMAIL=rijal9246@gmail.com
      # /END NGINX-PROXY ENVIRONMENT VARIABLES
    expose:
      - 80

networks:
  app-network:
    driver: bridge
  default:
    external:
      name: nginx-proxy

volumes:
  db_data:
