version: "3.7"

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    image: ijull/db-movie:latest
    restart: always
    ports:
      - "6603:3306"
    environment:
      MYSQL_DATABASE: bioskop
      MYSQL_USER: ijulll
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    build:
      context: .
      dockerfile: Dockerfile
    image: ijull/phpmyadmin-movie:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
