version: "3.7"

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "6603:3306"
    environment:
      MYSQL_DATABASE: clean
      MYSQL_USER: ijulll
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  db_data:
